//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordMetaViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordMetaViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  {
        ///    &quot;id&quot;: 3273601024,
        ///    &quot;serviceId&quot;: 1024,
        ///    &quot;networkId&quot;: 32736,
        ///    &quot;name&quot;: &quot;ＮＨＫ総合１・東京&quot;,
        ///    &quot;remoteControlKeyId&quot;: 1,
        ///    &quot;hasLogoData&quot;: true,
        ///    &quot;channelType&quot;: &quot;GR&quot;,
        ///    &quot;channelTypeId&quot;: 0,
        ///    &quot;channel&quot;: &quot;14&quot;,
        ///    &quot;type&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 3273601025,
        ///    &quot;serviceId&quot;: 1025,
        ///    &quot;networkId&quot;: 32736,
        ///    &quot;name&quot;: &quot;ＮＨＫ総合２・東京&quot;,
        ///    &quot;remoteControlKeyId&quot;: 1,
        ///    &quot;hasLogoData&quot;: true,
        ///    &quot;channelType&quot;: &quot;GR&quot;,
        ///    &quot;channelTypeId&quot;: 0,
        ///    &quot;channel&quot;: &quot;14&quot;,
        ///    &quot;type&quot;: 1
        ///  },
        ///  { [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ChannelPrefix {
            get {
                return ResourceManager.GetString("ChannelPrefix", resourceCulture);
            }
        }
    }
}
